'use strict';

const {
  Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
  HeadingLevel, AlignmentType, BorderStyle, ShadingType, WidthType,
  Header, Footer, PageNumber, NumberFormat
} = require('docx');
const archiver = require('archiver');
const { PassThrough } = require('stream');

const BRAND = {
  name: 'Enablerz Consulting & Solutions',
  footer: 'Generated by Enablerz BCM Simulation',
  primary: '1B3A5C',
  teal: '1A7A6E',
  amber: 'E8A020',
  grey: 'D1D5DB',
  lightGrey: 'F3F4F6'
};

function greyBox(text) {
  return new Paragraph({
    children: [new TextRun({ text: `[ ${text} ]`, color: '6B7280', italics: true })],
    shading: { type: ShadingType.SOLID, color: BRAND.lightGrey },
    spacing: { before: 100, after: 100 },
    indent: { left: 200, right: 200 }
  });
}

function heading1(text) {
  return new Paragraph({
    text,
    heading: HeadingLevel.HEADING_1,
    spacing: { before: 400, after: 200 },
    shading: { type: ShadingType.SOLID, color: BRAND.primary },
    children: [new TextRun({ text, color: 'FFFFFF', bold: true, size: 28 })]
  });
}

function heading2(text) {
  return new Paragraph({
    children: [new TextRun({ text, bold: true, size: 24, color: BRAND.teal })],
    spacing: { before: 300, after: 100 }
  });
}

function para(text, opts = {}) {
  return new Paragraph({
    children: [new TextRun({ text, ...opts })],
    spacing: { before: 80, after: 80 }
  });
}

function labelValue(label, value) {
  return new Paragraph({
    children: [
      new TextRun({ text: label + ': ', bold: true }),
      new TextRun({ text: value || '—' })
    ],
    spacing: { before: 60, after: 60 }
  });
}

function simpleTable(headers, rows) {
  const headerRow = new TableRow({
    children: headers.map(h => new TableCell({
      children: [new Paragraph({ children: [new TextRun({ text: h, bold: true, color: 'FFFFFF' })] })],
      shading: { type: ShadingType.SOLID, color: BRAND.primary }
    }))
  });
  const dataRows = rows.map(row => new TableRow({
    children: row.map(cell => new TableCell({
      children: [new Paragraph({ children: [new TextRun({ text: String(cell ?? '—') })] })]
    }))
  }));
  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [headerRow, ...dataRows]
  });
}

function confidentialHeader(companyName) {
  return new Header({
    children: [new Paragraph({
      children: [new TextRun({ text: `CONFIDENTIAL — BCM Planning Document | ${companyName}`, size: 18, color: '6B7280' })],
      alignment: AlignmentType.CENTER
    })]
  });
}

function pageFooter(date) {
  return new Footer({
    children: [new Paragraph({
      children: [new TextRun({ text: `${BRAND.footer} | ${date}`, size: 16, color: '6B7280' })],
      alignment: AlignmentType.CENTER
    })]
  });
}

// ─── Department criticality ───────────────────────────────────────────────────

function getDeptCriticality(deptName, waveHistory) {
  const count = waveHistory.filter(w => w.wave?.departments_activated?.includes(deptName)).length;
  if (count >= 3) return 'Critical';
  if (count >= 1) return 'Important';
  return 'Supporting';
}

// ─── Document 1: BIA ──────────────────────────────────────────────────────────

function buildBIA(team, session, finalScore, date) {
  const scenario = session.scenario;
  const templateKey = scenario.debrief_template;
  const template = session.scenario ? require('./data/scenario_database.json').debrief_templates[templateKey] : {};
  const waveHistory = team.leverHistory || [];

  const children = [
    // Cover header
    new Paragraph({
      children: [new TextRun({ text: BRAND.name, bold: true, size: 32, color: BRAND.primary })],
      alignment: AlignmentType.CENTER, spacing: { before: 0, after: 200 }
    }),
    new Paragraph({
      children: [new TextRun({ text: template.document_title || 'Business Impact Analysis', bold: true, size: 40 })],
      alignment: AlignmentType.CENTER, spacing: { after: 100 }
    }),
    new Paragraph({
      children: [new TextRun({ text: team.name, size: 28, color: BRAND.teal })],
      alignment: AlignmentType.CENTER, spacing: { after: 400 }
    }),

    heading1('1. Company Profile'),
    labelValue('Company Name', team.name),
    labelValue('Industry', session.industryId),
    labelValue('Company Archetype', team.archetype),
    labelValue('Headcount Band', team.headcount),
    labelValue('Scenario Played', scenario.name),
    labelValue('Session Date', date),
    greyBox('Actual annual revenue figures — to be completed by your Finance team'),
    greyBox('Named responsible personnel per department — to be completed'),

    heading1('2. Critical Functions'),
    heading2('Department Criticality Ranking'),
    simpleTable(
      ['Department', 'Criticality', 'Waves Active'],
      (team.departments || []).map(dept => {
        const critCount = waveHistory.filter(w => w.wave?.departments_activated?.includes(dept)).length;
        return [dept, getDeptCriticality(dept, waveHistory), `${critCount} of ${scenario.escalation_waves.length}`];
      })
    ),
    greyBox('Specific IT systems and asset inventory — to be completed by IT team'),

    heading1('3. Threat Assessment'),
    labelValue('Primary Threat', scenario.name),
    para(scenario.threat_summary),
    labelValue('Severity', scenario.severity),
    labelValue('War Chest Impact', scenario.war_chest_impact_label),
    greyBox('Vendor and supplier contact details — to be completed'),

    heading1('4. Impact Analysis Table'),
    simpleTable(
      ['Dimension', 'Starting Score', 'Points Lost', 'Final Score', 'Severity'],
      ['financial', 'regulatory', 'reputation', 'operational'].map(dim => {
        const start = 25;
        const final = finalScore.scores[dim] ?? 25;
        const lost = Math.max(0, start - final);
        const severity = lost >= 15 ? 'High' : lost >= 8 ? 'Medium' : 'Low';
        return [
          dim.charAt(0).toUpperCase() + dim.slice(1),
          start,
          lost,
          final,
          severity
        ];
      })
    ),

    heading1('5. Maximum Tolerable Downtime'),
    para('Based on simulation performance, the first critical threshold breach occurred at:'),
    ...(() => {
      const breachWave = findFirstBreachWave(team, scenario);
      return [
        para(breachWave ? `Wave ${breachWave.wave} — ${breachWave.time_label}` : 'No critical breach recorded during this simulation.', { bold: true }),
        greyBox('Actual Recovery Time Objective (RTO) — to be confirmed with department heads')
      ];
    })(),

    heading1('6. Recovery Priorities'),
    heading2('Actions Taken Successfully'),
    ...(finalScore.successfulLevers.length > 0
      ? finalScore.successfulLevers.map(id => {
          const lever = scenario.recovery_levers.find(l => l.id === id);
          return para(`✓  ${lever?.label || id} — ${lever?.description || ''}`, { color: '059669' });
        })
      : [para('No recovery actions were successfully executed.', { color: 'DC2626' })]),

    heading2('Gaps to Address'),
    ...(() => {
      const missedIds = scenario.recovery_levers
        .filter(l => !finalScore.successfulLevers.includes(l.id))
        .map(l => para(`✗  ${l.label} — ${l.description}`, { color: 'DC2626' }));
      const failedNotes = (finalScore.failedLevers || []).map(f =>
        para(`⚠  ${f.label}: ${f.reason}`, { color: 'D97706' })
      );
      return [...missedIds, ...failedNotes];
    })(),

    para(''),
    para(scenario.debrief_notes, { italics: true, color: '6B7280' }),

    greyBox('Alternate site address — to be confirmed with Operations'),
    greyBox('Named alternates and deputies per department — to be completed by HR')
  ];

  return new Document({
    sections: [{
      headers: { default: confidentialHeader(team.name) },
      footers: { default: pageFooter(date) },
      children
    }]
  });
}

function findFirstBreachWave(team, scenario) {
  if (!team.leverHistory) return null;
  for (const h of team.leverHistory) {
    for (const dim of ['financial', 'regulatory', 'reputation', 'operational']) {
      if ((h.scores?.[dim] ?? 25) < 15) {
        return scenario.escalation_waves[h.wave - 1] || null;
      }
    }
  }
  return null;
}

// ─── Document 2: Department Recovery Plan ─────────────────────────────────────

function buildRecoveryPlan(team, session, finalScore, date) {
  const scenario = session.scenario;
  const activatedDepts = Array.from(team.activatedDepartments || []);
  const members = Array.isArray(team.members) ? team.members : [];

  const children = [
    new Paragraph({
      children: [new TextRun({ text: BRAND.name, bold: true, size: 28, color: BRAND.primary })],
      alignment: AlignmentType.CENTER, spacing: { after: 100 }
    }),
    new Paragraph({
      children: [new TextRun({ text: 'Department Recovery Plan Draft', bold: true, size: 36 })],
      alignment: AlignmentType.CENTER, spacing: { after: 100 }
    }),
    new Paragraph({
      children: [new TextRun({ text: team.name, size: 24, color: BRAND.teal })],
      alignment: AlignmentType.CENTER, spacing: { after: 400 }
    })
  ];

  if (activatedDepts.length === 0) {
    children.push(para('No departments were activated during this simulation.'));
  }

  for (const dept of activatedDepts) {
    const assignedMember = members.find(m => m.department === dept);
    const wavesNeeded = scenario.escalation_waves
      .filter(w => w.departments_activated.includes(dept))
      .map(w => `Wave ${w.wave} (${w.time_label})`).join(', ');
    const relatedLevers = scenario.recovery_levers.filter(l => l.departments_required.includes(dept));
    const depsNeeded = [...new Set(relatedLevers.flatMap(l => l.departments_required).filter(d => d !== dept))];

    children.push(
      heading1(dept),
      labelValue('Assigned Team Member', assignedMember?.name || '(none assigned)'),
      labelValue('Waves Where This Department Was Needed', wavesNeeded || 'None'),

      heading2('Recovery Levers Requiring This Department'),
      simpleTable(
        ['Lever', 'Cost (RM)', 'Activated?', 'Outcome'],
        relatedLevers.map(l => {
          const wasUsed = finalScore.successfulLevers?.includes(l.id);
          const wasFailed = finalScore.failedLevers?.find(f => f.id === l.id);
          const status = wasUsed ? 'Yes — Success' : wasFailed ? 'Attempted — Failed' : 'Not Activated';
          return [l.label, l.war_chest_cost.toLocaleString(), status, wasUsed ? '' : (wasFailed?.reason || l.if_department_missing)];
        })
      ),

      heading2('Department Dependencies'),
      depsNeeded.length > 0
        ? para('This department requires collaboration with: ' + depsNeeded.join(', '))
        : para('No cross-department dependencies for this department.'),

      greyBox('Specific SOPs and step-by-step procedures — to be documented by department head'),
      greyBox('Named alternates and deputies — to be confirmed'),
      greyBox('Escalation contact list — to be completed'),
      greyBox('Recovery Time Objective (RTO) — actual target to be set')
    );
  }

  return new Document({
    sections: [{
      headers: { default: confidentialHeader(team.name) },
      footers: { default: pageFooter(date) },
      children
    }]
  });
}

// ─── Document 3: Scorecard ────────────────────────────────────────────────────

function buildScorecard(team, session, finalScore, date) {
  const scenario = session.scenario;
  const dims = ['financial', 'regulatory', 'reputation', 'operational'];
  const dimLabels = { financial: 'Financial Health', regulatory: 'Regulatory Standing', reputation: 'Reputation Index', operational: 'Operational Continuity' };

  function scoreBar(score) {
    const filled = Math.round(score / 5);
    const empty = 20 - filled;
    return '█'.repeat(filled) + '░'.repeat(empty) + ` ${score}/100`;
  }

  const wellDone = (finalScore.successfulLevers || []).slice(0, 3).map(id => {
    const lever = scenario.recovery_levers.find(l => l.id === id);
    return para(`• ${lever?.label || id}`, { color: '059669' });
  });
  if (wellDone.length === 0) wellDone.push(para('• No recovery actions were successfully executed.'));

  const gaps = scenario.recovery_levers
    .filter(l => !(finalScore.successfulLevers || []).includes(l.id))
    .slice(0, 3)
    .map(l => para(`• ${l.label}`, { color: 'DC2626' }));
  if (gaps.length === 0) gaps.push(para('• All recovery levers were activated — excellent resilience!', { color: '059669' }));

  const children = [
    new Paragraph({
      children: [new TextRun({ text: BRAND.name, bold: true, size: 28, color: BRAND.primary })],
      alignment: AlignmentType.CENTER, spacing: { after: 100 }
    }),
    new Paragraph({
      children: [new TextRun({ text: 'Resilience Scorecard', bold: true, size: 40 })],
      alignment: AlignmentType.CENTER, spacing: { after: 50 }
    }),
    new Paragraph({
      children: [new TextRun({ text: team.name, size: 28, color: BRAND.teal, bold: true })],
      alignment: AlignmentType.CENTER, spacing: { after: 50 }
    }),
    new Paragraph({
      children: [new TextRun({ text: `Scenario: ${scenario.name}  |  Date: ${date}`, size: 20, color: '6B7280' })],
      alignment: AlignmentType.CENTER, spacing: { after: 400 }
    }),

    new Paragraph({
      children: [new TextRun({ text: `FINAL RESILIENCE SCORE: ${finalScore.resilience}`, bold: true, size: 48, color: BRAND.primary })],
      alignment: AlignmentType.CENTER, spacing: { before: 200, after: 400 }
    }),

    heading2('Score by Dimension'),
    ...dims.map(dim => new Paragraph({
      children: [
        new TextRun({ text: `${dimLabels[dim]}: `, bold: true }),
        new TextRun({ text: scoreBar(finalScore.scores[dim] ?? 0), font: 'Courier New' })
      ],
      spacing: { before: 80, after: 80 }
    })),

    new Paragraph({ children: [new TextRun({ text: '' })], spacing: { before: 200, after: 100 } }),
    heading2('Recovery Turnaround'),
    para(`${finalScore.recoveryTurnaround}% of waves had at least one action taken`),

    heading2('War Chest'),
    simpleTable(
      ['Started (RM)', 'Spent (RM)', 'Remaining (RM)', 'Bonus Points'],
      [[
        finalScore.warChest.starting.toLocaleString(),
        finalScore.warChest.spent.toLocaleString(),
        finalScore.warChest.remaining.toLocaleString(),
        `+${finalScore.warChestBonus ?? 0} to Financial`
      ]]
    ),

    heading2('What Went Well'),
    ...wellDone,

    heading2('Gaps to Address'),
    ...gaps,

    new Paragraph({ children: [new TextRun({ text: '' })], spacing: { before: 400 } }),
    new Paragraph({
      children: [new TextRun({ text: `${BRAND.footer} | ${BRAND.name}`, size: 16, color: '6B7280', italics: true })],
      alignment: AlignmentType.CENTER
    })
  ];

  return new Document({
    sections: [{
      headers: { default: confidentialHeader(team.name) },
      footers: { default: pageFooter(date) },
      children
    }]
  });
}

// ─── ZIP all reports ──────────────────────────────────────────────────────────

async function generateReports(session, finalScores) {
  const date = new Date().toLocaleDateString('en-MY', { year: 'numeric', month: 'long', day: 'numeric' });

  return new Promise(async (resolve, reject) => {
    const passThrough = new PassThrough();
    const chunks = [];
    passThrough.on('data', chunk => chunks.push(chunk));
    passThrough.on('end', () => resolve(Buffer.concat(chunks)));
    passThrough.on('error', reject);

    const zip = archiver('zip', { zlib: { level: 6 } });
    zip.pipe(passThrough);
    zip.on('error', reject);

    for (const teamScore of finalScores) {
      const team = session.teams.get(teamScore.teamId);
      if (!team) continue;

      // Attach members array for convenience
      team.members = Array.isArray(team.members) ? team.members : Array.from(team.members?.values?.() || []);

      const safeName = team.name.replace(/[^a-zA-Z0-9_\- ]/g, '').slice(0, 30);

      const biaDoc = buildBIA(team, session, teamScore, date);
      const recDoc = buildRecoveryPlan(team, session, teamScore, date);
      const scoreDoc = buildScorecard(team, session, teamScore, date);

      const [biaBuf, recBuf, scoreBuf] = await Promise.all([
        Packer.toBuffer(biaDoc),
        Packer.toBuffer(recDoc),
        Packer.toBuffer(scoreDoc)
      ]);

      zip.append(biaBuf, { name: `${safeName}/01_BIA_Template.docx` });
      zip.append(recBuf, { name: `${safeName}/02_Recovery_Plan.docx` });
      zip.append(scoreBuf, { name: `${safeName}/03_Scorecard.docx` });
    }

    await zip.finalize();
  });
}

module.exports = { generateReports };
